config/routes.rb
Harjutus::Application.routes.draw do
  
  resources :posts, only: [:new, :create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :movies
  resources :shows
  resources :reviews
  
  
  get "posts/new"
  get "form/home"
  post "form/home"
  get "form/converter"
  post "form/converter"
  get "form/about"
  root 'form#home'
  require 'net/http'
  match "/signout", to: 'sessions#destroy', via: :delete
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  before_save { self.email = email.downcase}
  before_create :create_remember_token
  has_secure_password
  
  before_validation :downcase_email
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 3}
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
private
  def downcase_email
    self.remember_token = User.encrypt(User.new_remember_token)
    self.email = self.email.downcase if self.email.present?
  end
  def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index,:edit,:update, :destroy]
  before_action :correct_user, only: [:edit,:update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Registration was successful!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    
  end
  
  def update
    
    if @user.update_attributes(user_params)
      flash[:success] = "Update successful"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted."
    redirect_to users_url
  end
  # Private section, makes the page unable to be seen for non logged in users
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
   def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  # Redirecting not logged in user etc.
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to '/sessions/new', notice: "Please sign in!"
    end
    
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_post.html.erb
<%= post.content %>

app/views/users/_user.html.erb
 <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit account") %>

<h2 align="center">Edit your account information here:	</h2>
	
<%= form_for(@user) do |f| %>
	<div class="forms">
	<%= render 'shared/error_messages' %>
	<%= f.text_field :email, placeholder: "Email..." %>
	<%= f.text_field :name, placeholder: "Name..."%>
	<%= f.password_field :password, placeholder: "Password..."%>
	<%= f.password_field :password_confirmation, placeholder: "Password confirmation..." %></br>
	<%= f.submit "Save changes"%>
	</div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h2 align="center">All users</h2></br><b>(Click on an user to see more info about them and to see all the posts they have made on this page)</b>

<table align="center">
	<tr>
		<td align="left"><b>Name</b></td>
		<td align="left"><b>Joined</b></td>
		<% if current_user.admin? && !current_user?(@user) %>
		<td align="left"><b>Admin functions</b></td>
		<% end %>
	</tr>
  <% @users.each do |user| %>
 	<tr>
 		<td align="left"><%= link_to user.name.capitalize, user, class: "black" %></td>
 		<td align="left"><%= link_to user.created_at, user, class: "black" %></td>
	<% if current_user.admin? && !current_user?(@user) %>
		<td>
			<%= link_to "Delete this user", user, method: :delete, class: "black", data: { confirm: "You sure?" } %>
  		</td>
  	<% end %>
 	</tr>
 <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, "Create an account") %>

<b align="center">Account creation</b></br>
<b align="center">Fill out the forms below	</b>

<%= form_for(@user) do |f| %>
	<div class="forms">
	<%= render 'shared/error_messages' %>
	<%= f.text_field :email, placeholder: "Email..." %>
	<%= f.text_field :name, placeholder: "Name..."%>
	<%= f.password_field :password, placeholder: "Password..."%>
	<%= f.password_field :password_confirmation, placeholder: "Password confirmation..." %></br>
	<%= f.submit "Register my Account"%>
	
	</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name.capitalize) %>

<h2 align="center">User information:</h2>

<table align="center">
	<tr>
		<td align="left"><b>Name</b></td>
		<td align="left"><b>Email</b></td>
		<td align="left"><b>Created</b></td>
		<td align="left"><b>Updated</b></td>
	</tr>
 	<tr>
 		<td align="left"><%= @user.name.capitalize %></td>
 		<td align="left"><%= @user.email %></td>
 		<td align="left"><%= @user.created_at %></td>
 		<td align="left"><%= @user.updated_at %></td>
 	</tr>
</table>
<% if @user.posts.any? %>
      	<h3>This user has made(<%= @user.posts.count %>) posts</h3>
<table align="center">
	<tr>
		<td align="left"><b>Content of the post</b></td>
		<td align="left"><b>Created</b></td>
		<td align="left"><b>Destroy post</b></td>
	</tr>
 		 <% @posts.each do |i| %>
 		 	<tr>
 		 	<td align="left"><%= i.content.capitalize %></td>
 		 	<td><%= i.created_at %></td>
			<td><%= link_to "Delete this post", post_path(i), method: :delete, class: "black", data: { confirm: "You sure?" } %></td>
 		 <% end %>
    	<% end %>
    </tr>
</table>