config/routes.rb
Harjutus::Application.routes.draw do
  
  resources :posts, only: [:new, :create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :movies
  resources :shows
  resources :reviews
  
  
  get "posts/new"
  get "form/home"
  post "form/home"
  get "form/converter"
  post "form/converter"
  get "form/about"
  root 'form#home'
  require 'net/http'
  match "/signout", to: 'sessions#destroy', via: :delete
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :signed_in_user, only: [:index,:edit,:update, :destroy]
  before_action :admin_user,     only: :destroy
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  def index
    @reviews = Review.all
  end
  
  def show
    @review = Review.find(params[:id])
  end
  
  def new
    @review = current_user.reviews.build
  end
  
  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = "Review created!"
      redirect_to reviews_path
    else
      flash[:success] = "Did you leave a field empty? All fields must be filled before we can accept the review!"
      render new_review_path
    end
  end
  
  def update
    if @review.update_attributes(review_params)
      flash[:success] = "Update successful"
      redirect_to @review
    else
      render 'edit'
    end
  end
  
  def edit
    
  end
  
  def destroy
    Review.find(params[:id]).destroy
    flash[:success] = "Review deleted from the database."
    redirect_to reviews_path
  end
 
  # Private section, makes the page unable to be seen for non logged in users
  private
  def review_params
    params.require(:review).permit(:heading, :content, :user_id, :about)
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
   def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  # Redirecting not logged in user etc.
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to '/sessions/new', notice: "Please sign in!"
    end
    
  end
  
  def set_review
    @review = Review.find(params[:id])
  end
  
end

app/views/reviews/edit.html.erb
<% provide(:title, "Edit movie") %>
<p class="content">
	<p class="text">
		Edit review here:	
	</p>
<%= form_for @review do |f| %>
    	<div class="forms">
    		<%= f.text_field :heading, placeholder: "Type in the heading for your review...", autofocus: true %>
			<%= f.text_area :about, placeholder: "What movie is your review about..." %>
			<%= f.text_area :content, placeholder: "Type in the content for your review..." %>
			<%= f.submit 'Submit!' %>
			<%= link_to "Back to movies", movies_path, class: "black" %>
		</div>
	<% end %>

app/views/reviews/index.html.erb
<% provide(:title, 'Reviews') %>

<h2 align="center">A list of reviews</h2>

<table align="center">
	<tr>
		<td align="left"><b>Heading</b></td>
		<td align="left"><b>Written by</b></td>
		<% if current_user.admin? && !current_user?(@user) %>
		<td align="left"><b>Admin functions</b></td>
		<% end %>
	</tr>
  <% @reviews.each do |review| %>
 	<tr>
 		<td align="left"><%= link_to review.heading.capitalize, review, class: "black" %></td>
 		<td align="left"><%= link_to review.user.name, review.user, class: "black" %></td>	
	<% if current_user.admin? && !current_user?(@user) %>
		<td>
			<%= link_to "Delete this review", review, method: :delete, class: "black", data: { confirm: "You sure?" } %>
  		</td>
  	<% end %>
 	</tr>
 <% end %>
</table>
<p class="text">
	<%= link_to "Want to write a review about a movie? Click here!!", new_review_path, class: "black" %>
</p>

app/views/reviews/new.html.erb
<% provide(:title, "Create a review") %>

<p class="text">
    <b>Write a new review:</b>
    <%= form_for(@review) do |f| %>
    	<div class="forms">
			<%= f.text_field :heading, placeholder: "Type in the heading for your review...", autofocus: true %>
			<%= f.text_area :about, placeholder: "What movie is your review about..." %>
			<%= f.text_area :content, placeholder: "Type in the content for your review..." %>
			<%= f.submit 'Submit!' %>
		</div>
	<% end %>
</p>

app/views/reviews/show.html.erb
<% provide(:title, @review.heading.capitalize) %>

<h2 align="center">About the review</h2>

<table align="center">
	<tr>
		<td align="left"><b>Heading</b></td>
		<td align="left"><b>Review is about</b></td>
		<td align="left"><b>Created</b></td>
		<td align="left"><b>Created by</b></td>
		
	</tr>
 	<tr>
 		<td align="left"><%= @review.heading.capitalize %></td>
 		<td align="left"><%= @review.about.capitalize %></td>
 		<td align="left"><%= @review.created_at %></td>
 		<td align="left"><%= @review.user.name.capitalize %></td>
 	</tr>
 	<tr>
 		<td align="left"><b>The review:</b></td>
 	</tr>
 	<tr>
 		<td><%= @review.content.capitalize %><td>
 	</tr>
</table>

<%= link_to "Edit review", edit_review_path, class: "black" %> or
<%= link_to "Back to previous page", reviews_path, class: "black" %>