config/routes.rb
Harjutus::Application.routes.draw do
  
  resources :posts, only: [:new, :create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :movies
  resources :shows
  resources :reviews
  
  
  get "posts/new"
  get "form/home"
  post "form/home"
  get "form/converter"
  post "form/converter"
  get "form/about"
  root 'form#home'
  require 'net/http'
  match "/signout", to: 'sessions#destroy', via: :delete
  
end

app/views/layouts/_footer.html.erb
<p class="footer">
  Page created by: Kaspar | veske@tlu.ee |
</p>

app/views/layouts/_menu.html.erb
<div id='cssmenu'>
<ul>
   <li class='active'><%= link_to 'Main page', form_home_path %></li>
   <li class='has-sub'><%= link_to 'Converter/Databases', form_converter_path %>
      <ul>
         <li class='active'><%= link_to 'Movies', movies_path %></li>
         <li class='active'><%= link_to 'Shows', shows_path %></li>
         <li class='active'><%= link_to 'Reviews', reviews_path %></li>   
      </ul>
   </li>
   <li class='has-sub'><%= link_to "Users", users_path %>
   	<ul>
   		<% if signed_in? %>
   		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Make new posts", posts_new_path %></li>
		<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
		<% else %>
		<li><%= link_to 'Log in', new_session_path %></li>
		<% end %>
   	</ul>
   </li>
   <li class='last'><%= link_to 'About page', form_about_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forms | <%= yield(:title)%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans'>
</head>
<body>
<%= render "layouts/menu"%>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>